"""
"""

import pytest


@pytest.fixture()
def farms():
    return (
        {'filename_1': 'MAF32-194-1_59.tif', 'filename_2': 'MAF32-194-1_60.tif', 'document_type': 'B496/EI', 'county': 'WD Westmorland', 'parish': '1 Ambleside', 'primary_farm_number': '18', 'additional_farms': '', 'farm_name': 'The Grove Farm', 'addressee_title': '', 'addressee_individual_name': '', 'addressee_group_names': '', 'address': '', 'owner_title': 'Rev', 'owner_individual_name': 'H R Fleming', 'owner_group_names': '*', 'owner_address': 'Rayrigg Hall, Windermere, Westmorland', 'farmer_title': '*', 'farmer_individual_name': 'R Nicholson', 'farmer_group_names': '*', 'farmer_address': 'The Grove Farm, Ambleside', 'acreage': '162.5/886.5/1049', 'OS_map_sheet': '26 NE', 'field_info_date': '06-Feb-42', 'primary_record_date': '12-Feb-43', '': ''},
        {'filename_1': 'MAF32-194-1_75.tif', 'filename_2': 'MAF32-194-1_76.tif', 'document_type': 'C 47/SSY', 'county': 'WD Westmorland', 'parish': '1 Ambleside', 'primary_farm_number': '19', 'additional_farms': '', 'farm_name': '', 'addressee_title': 'Mr', 'addressee_individual_name': 'W Parsons', 'addressee_group_names': '*', 'address': 'Gale House, Ambleside, Westmorland', 'owner_title': '', 'owner_individual_name': '', 'owner_group_names': '', 'owner_address': '', 'farmer_title': '', 'farmer_individual_name': '', 'farmer_group_names': '', 'farmer_address': '', 'acreage': '', 'OS_map_sheet': '', 'field_info_date': '', 'primary_record_date': '', '': ''},
        {'filename_1': 'MAF32-228-1_23.tif', 'filename_2': 'MAF32-228-1_24.tif', 'document_type': 'B496/EI', 'county': 'DM Durham', 'parish': '1 Barnard Castle', 'primary_farm_number': '4', 'additional_farms': '', 'farm_name': '9 King Street', 'addressee_title': '', 'addressee_individual_name': '', 'addressee_group_names': '', 'address': '', 'owner_title': '*', 'owner_individual_name': '*', 'owner_group_names': 'Mr Kellett; Mr Swift; Mr W Bain; Mrs Mane; Mrs Todd; W Walton', 'owner_address': '8 Sendal, Yorkshire; Barnard Castle; Darlington Road, Barnard Castle; Gallowgate, Barnard Castle; Gallowgate, Barnard Castle; 24 Coronation Road, Redcar', 'farmer_title': '*', 'farmer_individual_name': 'W J Chaplow', 'farmer_group_names': '*', 'farmer_address': 'Barnard Castle', 'acreage': '30/Nil Acres', 'OS_map_sheet': 'XL NE 1898', 'field_info_date': '*', 'primary_record_date': '19 April 1943', '': ''},
        {'filename_1': 'MAF32-247-23_75.tif', 'filename_2': 'MAF32-247-23_76.tif', 'document_type': 'B496/EI', 'county': 'RD Rutland', 'parish': '23 Hambleton', 'primary_farm_number': '19', 'additional_farms': '', 'farm_name': 'Armley Lodge', 'addressee_title': '', 'addressee_individual_name': '', 'addressee_group_names': '', 'address': '', 'owner_title': '*', 'owner_individual_name': '*', 'owner_group_names': 'Nichols, Agent for the Earl of Ancaster', 'owner_address': 'Hambleton, Oakham', 'farmer_title': '*', 'farmer_individual_name': '*', 'farmer_group_names': 'Woodhead Bros', 'farmer_address': 'Hambleton, Oakham', 'acreage': 'Arable 127.5; Grass 45; 172.5', 'OS_map_sheet': '9 NE1931 Edition', 'field_info_date': '30 January 1942', 'primary_record_date': '*'},
        )

